import type { Exercise } from "@gymfit/shared";

/**
 * Curated exercise library. IDs are stable slugs referenced by plans and
 * history, so never rename an ID once it has shipped — add a new one instead.
 *
 * `equipment` lists everything required. `contraindications` lists the
 * user-selected movement limitations that exclude the exercise; they are
 * conservative filters, not medical guidance.
 */
type Seed = Omit<Exercise, "secondaryMuscles" | "contraindications" | "loaded" | "measure" | "category" | "videoUrl"> &
  Partial<Pick<Exercise, "secondaryMuscles" | "contraindications" | "loaded" | "measure" | "category" | "videoUrl">>;

const LOADED_EQUIPMENT = new Set(["barbell", "dumbbell", "machine", "cable", "kettlebell"]);

function ex(s: Seed): Exercise {
  return {
    category: "strength",
    measure: "reps",
    secondaryMuscles: [],
    contraindications: [],
    videoUrl: null,
    loaded: s.equipment.some((e) => LOADED_EQUIPMENT.has(e)),
    ...s,
  };
}

export const EXERCISE_SEED: Exercise[] = [
  /* ---------------- Horizontal push ---------------- */
  ex({
    id: "barbell-bench-press",
    name: "Barbell Bench Press",
    pattern: "horizontal_push",
    mechanics: "compound",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    instructions: [
      "Lie on a flat bench with your eyes under the bar and feet flat on the floor.",
      "Grip the bar slightly wider than shoulder width, squeeze your shoulder blades together.",
      "Unrack and lower the bar under control to your mid/lower chest.",
      "Press the bar back up over your shoulders until your arms are straight.",
      "Use a spotter or safety arms when working near your limit.",
    ],
    commonMistakes: [
      "Bouncing the bar off the chest.",
      "Flaring elbows straight out to 90°.",
      "Lifting the hips off the bench.",
    ],
  }),
  ex({
    id: "incline-barbell-bench-press",
    name: "Incline Barbell Bench Press",
    pattern: "horizontal_push",
    mechanics: "compound",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    instructions: [
      "Set the bench to roughly 30–45° incline.",
      "Grip slightly wider than shoulder width and retract your shoulder blades.",
      "Lower the bar to your upper chest under control.",
      "Press up and slightly back until your arms are straight.",
    ],
    commonMistakes: [
      "Setting the incline so steep it becomes a shoulder press.",
      "Arching excessively to turn it into a flat press.",
    ],
  }),
  ex({
    id: "dumbbell-bench-press",
    name: "Dumbbell Bench Press",
    pattern: "horizontal_push",
    mechanics: "compound",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    instructions: [
      "Sit on a flat bench with dumbbells on your thighs, then lie back bringing them to chest level.",
      "Press the dumbbells up until your arms are straight above your chest.",
      "Lower slowly until your elbows are slightly below the bench, keeping wrists stacked over elbows.",
      "No bench? Perform it as a floor press with the same cues.",
    ],
    commonMistakes: [
      "Letting the dumbbells drift too far apart at the bottom.",
      "Dropping the weights quickly instead of controlling the descent.",
    ],
  }),
  ex({
    id: "incline-dumbbell-press",
    name: "Incline Dumbbell Press",
    pattern: "horizontal_push",
    mechanics: "compound",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    instructions: [
      "Set a bench to about 30–45° incline.",
      "Start with the dumbbells at upper-chest level, palms facing forward or slightly inward.",
      "Press up until your arms are straight, without clanking the weights together.",
      "Lower under control back to the start.",
    ],
    commonMistakes: ["Using too steep an incline.", "Shrugging the shoulders toward the ears."],
  }),
  ex({
    id: "push-up",
    name: "Push-up",
    pattern: "horizontal_push",
    mechanics: "compound",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders", "core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    contraindications: ["avoid_floor_work", "wrist_friendly"],
    instructions: [
      "Place hands slightly wider than shoulder width, body in a straight line from head to heels.",
      "Brace your core and glutes.",
      "Lower your chest toward the floor with elbows about 45° from your body.",
      "Push back up to straight arms.",
    ],
    commonMistakes: ["Sagging hips.", "Only doing half the range of motion.", "Head dropping forward."],
  }),
  ex({
    id: "incline-push-up",
    name: "Incline Push-up",
    pattern: "horizontal_push",
    mechanics: "compound",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders", "core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    contraindications: ["wrist_friendly"],
    instructions: [
      "Place your hands on a sturdy elevated surface such as a bench, table or counter.",
      "Walk your feet back so your body forms a straight line.",
      "Lower your chest to the edge of the surface, then press back up.",
      "Lower the surface height over time to make it harder.",
    ],
    commonMistakes: ["Using an unstable surface.", "Letting the hips sag."],
  }),
  ex({
    id: "machine-chest-press",
    name: "Machine Chest Press",
    pattern: "horizontal_push",
    mechanics: "compound",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: ["machine"],
    difficulty: "beginner",
    instructions: [
      "Adjust the seat so the handles line up with your mid-chest.",
      "Sit with your back flat against the pad and shoulder blades pulled back.",
      "Press the handles forward until your arms are nearly straight.",
      "Return slowly until you feel a stretch across the chest.",
    ],
    commonMistakes: ["Seat set too high or low.", "Letting the weight stack slam between reps."],
  }),
  ex({
    id: "band-chest-press",
    name: "Resistance Band Chest Press",
    pattern: "horizontal_push",
    mechanics: "compound",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: ["resistance_band"],
    difficulty: "beginner",
    instructions: [
      "Anchor the band behind you at chest height (or wrap it around your upper back).",
      "Hold the handles at chest level with elbows about 45° from your body.",
      "Press forward until your arms are straight, then return slowly.",
    ],
    commonMistakes: ["Letting the band snap back.", "Arching the lower back."],
  }),
  ex({
    id: "dumbbell-fly",
    name: "Dumbbell Fly",
    pattern: "chest_isolation",
    mechanics: "isolation",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders"],
    equipment: ["dumbbell"],
    difficulty: "intermediate",
    instructions: [
      "Lie on a flat bench holding dumbbells above your chest, palms facing each other.",
      "With a slight bend in the elbows, open your arms in a wide arc.",
      "Lower until you feel a stretch in the chest without going past shoulder level.",
      "Bring the dumbbells back together along the same arc.",
    ],
    commonMistakes: ["Turning it into a press by bending the elbows a lot.", "Going too heavy and overstretching."],
  }),
  ex({
    id: "cable-chest-fly",
    name: "Cable Chest Fly",
    pattern: "chest_isolation",
    mechanics: "isolation",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders"],
    equipment: ["cable"],
    difficulty: "beginner",
    instructions: [
      "Set both pulleys at about shoulder height and stand in the middle with a staggered stance.",
      "With a slight elbow bend, bring the handles together in front of your chest.",
      "Return slowly until you feel a stretch across the chest.",
    ],
    commonMistakes: ["Leaning too far forward.", "Using momentum to swing the handles."],
  }),

  /* ---------------- Vertical push ---------------- */
  ex({
    id: "overhead-press",
    name: "Barbell Overhead Press",
    pattern: "vertical_push",
    mechanics: "compound",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps", "core"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    contraindications: ["avoid_overhead", "avoid_spinal_loading"],
    instructions: [
      "Start with the bar on your front shoulders, hands just outside shoulder width.",
      "Brace your core and squeeze your glutes.",
      "Press the bar straight up, moving your head back slightly to clear it.",
      "Finish with the bar over your mid-foot, then lower under control.",
    ],
    commonMistakes: ["Leaning back excessively.", "Pressing the bar forward instead of straight up."],
  }),
  ex({
    id: "seated-dumbbell-shoulder-press",
    name: "Seated Dumbbell Shoulder Press",
    pattern: "vertical_push",
    mechanics: "compound",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    contraindications: ["avoid_overhead"],
    instructions: [
      "Sit on an upright bench with dumbbells at shoulder height.",
      "Press the dumbbells overhead until your arms are straight.",
      "Lower back to shoulder height under control.",
    ],
    commonMistakes: ["Arching the lower back off the pad.", "Lowering only halfway."],
  }),
  ex({
    id: "machine-shoulder-press",
    name: "Machine Shoulder Press",
    pattern: "vertical_push",
    mechanics: "compound",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps"],
    equipment: ["machine"],
    difficulty: "beginner",
    contraindications: ["avoid_overhead"],
    instructions: [
      "Adjust the seat so the handles start at about shoulder height.",
      "Press upward until your arms are nearly straight.",
      "Lower slowly to the start position.",
    ],
    commonMistakes: ["Seat too low, causing a cramped start.", "Locking out aggressively."],
  }),
  ex({
    id: "band-overhead-press",
    name: "Resistance Band Overhead Press",
    pattern: "vertical_push",
    mechanics: "compound",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps"],
    equipment: ["resistance_band"],
    difficulty: "beginner",
    contraindications: ["avoid_overhead"],
    instructions: [
      "Stand on the middle of the band and hold the ends at shoulder height.",
      "Press overhead until your arms are straight.",
      "Lower slowly back to shoulder height.",
    ],
    commonMistakes: ["Leaning back.", "Letting the band pull your wrists backward."],
  }),
  ex({
    id: "pike-push-up",
    name: "Pike Push-up",
    pattern: "vertical_push",
    mechanics: "compound",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    contraindications: ["avoid_overhead", "avoid_floor_work", "wrist_friendly"],
    instructions: [
      "Start in a push-up position, then walk your feet in and lift your hips into an inverted V.",
      "Bend your elbows to lower the top of your head toward the floor between your hands.",
      "Press back up to straight arms.",
    ],
    commonMistakes: ["Letting the hips drop so it becomes a regular push-up.", "Flaring elbows wide."],
  }),

  /* ---------------- Shoulder isolation ---------------- */
  ex({
    id: "dumbbell-lateral-raise",
    name: "Dumbbell Lateral Raise",
    pattern: "shoulder_isolation",
    mechanics: "isolation",
    primaryMuscles: ["shoulders"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    instructions: [
      "Stand holding light dumbbells at your sides with a slight bend in the elbows.",
      "Raise your arms out to the side until they reach about shoulder height.",
      "Lower slowly.",
    ],
    commonMistakes: ["Swinging the body to lift the weight.", "Shrugging the shoulders up."],
  }),
  ex({
    id: "cable-lateral-raise",
    name: "Cable Lateral Raise",
    pattern: "shoulder_isolation",
    mechanics: "isolation",
    primaryMuscles: ["shoulders"],
    equipment: ["cable"],
    difficulty: "intermediate",
    instructions: [
      "Set a pulley at the lowest position and stand side-on to the machine.",
      "Hold the handle with the far hand and raise it out to the side to shoulder height.",
      "Lower under control and repeat, then switch sides.",
    ],
    commonMistakes: ["Leaning away to cheat the weight up.", "Raising above shoulder height with a shrug."],
  }),
  ex({
    id: "band-lateral-raise",
    name: "Resistance Band Lateral Raise",
    pattern: "shoulder_isolation",
    mechanics: "isolation",
    primaryMuscles: ["shoulders"],
    equipment: ["resistance_band"],
    difficulty: "beginner",
    instructions: [
      "Stand on the band and hold the ends at your sides.",
      "Raise your arms out to shoulder height with a slight elbow bend.",
      "Lower slowly against the band's tension.",
    ],
    commonMistakes: ["Using a band that is too heavy.", "Shrugging."],
  }),
  ex({
    id: "reverse-dumbbell-fly",
    name: "Reverse Dumbbell Fly",
    pattern: "shoulder_isolation",
    mechanics: "isolation",
    primaryMuscles: ["rear_delts"],
    secondaryMuscles: ["traps"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    instructions: [
      "Hinge forward at the hips with a flat back, dumbbells hanging below your chest.",
      "With a slight elbow bend, raise the dumbbells out to the sides.",
      "Squeeze between the shoulder blades, then lower slowly.",
    ],
    commonMistakes: ["Rounding the back.", "Using momentum from the torso."],
  }),
  ex({
    id: "face-pull",
    name: "Cable Face Pull",
    pattern: "shoulder_isolation",
    mechanics: "isolation",
    primaryMuscles: ["rear_delts"],
    secondaryMuscles: ["traps", "shoulders"],
    equipment: ["cable"],
    difficulty: "beginner",
    instructions: [
      "Attach a rope to a pulley at upper-chest or face height.",
      "Pull the rope toward your face, separating the ends and leading with your elbows high.",
      "Pause, then return slowly.",
    ],
    commonMistakes: ["Leaning back to use bodyweight.", "Pulling to the chest with low elbows."],
  }),
  ex({
    id: "band-pull-apart",
    name: "Band Pull-Apart",
    pattern: "shoulder_isolation",
    mechanics: "isolation",
    primaryMuscles: ["rear_delts"],
    secondaryMuscles: ["traps"],
    equipment: ["resistance_band"],
    difficulty: "beginner",
    instructions: [
      "Hold a band in front of you at shoulder height with straight arms.",
      "Pull the band apart by moving your hands out to the sides.",
      "Squeeze your shoulder blades, then return slowly.",
    ],
    commonMistakes: ["Bending the elbows a lot.", "Shrugging the shoulders."],
  }),

  /* ---------------- Horizontal pull ---------------- */
  ex({
    id: "barbell-row",
    name: "Barbell Bent-Over Row",
    pattern: "horizontal_pull",
    mechanics: "compound",
    primaryMuscles: ["back", "lats"],
    secondaryMuscles: ["biceps", "rear_delts", "lower_back"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    contraindications: ["avoid_spinal_loading"],
    instructions: [
      "Hold the bar with an overhand grip, hinge at the hips until your torso is about 45° or lower.",
      "Keep your back flat and core braced.",
      "Row the bar to your lower ribs, driving the elbows back.",
      "Lower under control.",
    ],
    commonMistakes: ["Rounding the lower back.", "Standing up more with each rep."],
  }),
  ex({
    id: "one-arm-dumbbell-row",
    name: "One-Arm Dumbbell Row",
    pattern: "horizontal_pull",
    mechanics: "compound",
    primaryMuscles: ["lats", "back"],
    secondaryMuscles: ["biceps", "rear_delts"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    instructions: [
      "Support yourself with one hand and knee on a bench (or one hand on a sturdy surface).",
      "Let the dumbbell hang straight down with a flat back.",
      "Pull the dumbbell toward your hip, keeping the elbow close.",
      "Lower fully and repeat, then switch sides.",
    ],
    commonMistakes: ["Twisting the torso to lift the weight.", "Pulling toward the chest instead of the hip."],
  }),
  ex({
    id: "seated-cable-row",
    name: "Seated Cable Row",
    pattern: "horizontal_pull",
    mechanics: "compound",
    primaryMuscles: ["back", "lats"],
    secondaryMuscles: ["biceps", "rear_delts"],
    equipment: ["cable"],
    difficulty: "beginner",
    instructions: [
      "Sit with feet on the platform and knees slightly bent, holding the handle.",
      "Sit tall and pull the handle to your lower ribs.",
      "Squeeze your shoulder blades together, then extend your arms slowly.",
    ],
    commonMistakes: ["Rocking the torso back and forth.", "Rounding the shoulders forward at the end."],
  }),
  ex({
    id: "chest-supported-machine-row",
    name: "Chest-Supported Machine Row",
    pattern: "horizontal_pull",
    mechanics: "compound",
    primaryMuscles: ["back", "lats"],
    secondaryMuscles: ["biceps", "rear_delts"],
    equipment: ["machine"],
    difficulty: "beginner",
    instructions: [
      "Adjust the seat so the chest pad sits at mid-chest.",
      "Grab the handles and pull your elbows back.",
      "Pause, then return slowly without letting the weight stack touch.",
    ],
    commonMistakes: ["Lifting the chest off the pad.", "Cutting the range of motion short."],
  }),
  ex({
    id: "band-row",
    name: "Resistance Band Row",
    pattern: "horizontal_pull",
    mechanics: "compound",
    primaryMuscles: ["back", "lats"],
    secondaryMuscles: ["biceps", "rear_delts"],
    equipment: ["resistance_band"],
    difficulty: "beginner",
    instructions: [
      "Anchor the band at chest height or loop it around your feet while seated.",
      "Pull the handles toward your lower ribs, squeezing your shoulder blades.",
      "Return slowly.",
    ],
    commonMistakes: ["Shrugging.", "Leaning back to create tension."],
  }),
  ex({
    id: "doorframe-row",
    name: "Doorframe Row",
    pattern: "horizontal_pull",
    mechanics: "compound",
    primaryMuscles: ["back", "lats"],
    secondaryMuscles: ["biceps", "forearms"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    instructions: [
      "Stand in a sturdy doorway and grip both sides of the frame at chest height.",
      "Walk your feet forward and lean back with straight arms and a straight body.",
      "Pull your chest toward the frame, then lower back slowly.",
      "Only use a solid frame; step your feet back to make it easier.",
    ],
    commonMistakes: ["Using a weak or loose door/frame.", "Bending at the hips instead of staying straight."],
  }),

  /* ---------------- Vertical pull ---------------- */
  ex({
    id: "pull-up",
    name: "Pull-up",
    pattern: "vertical_pull",
    mechanics: "compound",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "back", "forearms"],
    equipment: ["pullup_bar"],
    difficulty: "advanced",
    instructions: [
      "Hang from the bar with an overhand grip slightly wider than shoulder width.",
      "Pull your shoulder blades down and drive your elbows toward your ribs.",
      "Pull until your chin clears the bar, then lower to a full hang.",
    ],
    commonMistakes: ["Kipping or swinging.", "Half reps that never reach a full hang."],
  }),
  ex({
    id: "chin-up",
    name: "Chin-up",
    pattern: "vertical_pull",
    mechanics: "compound",
    primaryMuscles: ["lats", "biceps"],
    secondaryMuscles: ["back", "forearms"],
    equipment: ["pullup_bar"],
    difficulty: "intermediate",
    instructions: [
      "Hang from the bar with palms facing you, about shoulder width apart.",
      "Pull until your chin clears the bar.",
      "Lower under control to a full hang.",
    ],
    commonMistakes: ["Swinging the legs for momentum.", "Not lowering fully."],
  }),
  ex({
    id: "lat-pulldown",
    name: "Lat Pulldown",
    pattern: "vertical_pull",
    mechanics: "compound",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "back"],
    equipment: ["cable"],
    difficulty: "beginner",
    instructions: [
      "Sit with your thighs secured under the pads and grip the bar slightly wider than shoulders.",
      "Lean back slightly and pull the bar to your upper chest.",
      "Control the bar back up until your arms are straight.",
    ],
    commonMistakes: ["Pulling the bar behind the neck.", "Leaning far back and using momentum."],
  }),
  ex({
    id: "assisted-pull-up",
    name: "Assisted Pull-up Machine",
    pattern: "vertical_pull",
    mechanics: "compound",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "back"],
    equipment: ["machine"],
    difficulty: "beginner",
    loaded: false,
    instructions: [
      "Select an assistance weight (more weight = more help).",
      "Kneel or stand on the platform and grip the handles.",
      "Pull until your chin clears the handles, then lower under control.",
    ],
    commonMistakes: ["Relying on so much assistance there is no challenge.", "Rushing the descent."],
  }),
  ex({
    id: "band-lat-pulldown",
    name: "Resistance Band Lat Pulldown",
    pattern: "vertical_pull",
    mechanics: "compound",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "back"],
    equipment: ["resistance_band"],
    difficulty: "beginner",
    instructions: [
      "Anchor the band high (top of a door with a door anchor).",
      "Kneel facing the anchor and hold the band with straight arms overhead.",
      "Pull your elbows down toward your ribs, then return slowly.",
    ],
    commonMistakes: ["Anchoring the band insecurely.", "Shrugging instead of pulling the elbows down."],
  }),

  /* ---------------- Arms ---------------- */
  ex({
    id: "dumbbell-biceps-curl",
    name: "Dumbbell Biceps Curl",
    pattern: "elbow_flexion",
    mechanics: "isolation",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    instructions: [
      "Stand holding dumbbells at your sides, palms facing forward.",
      "Curl the weights up while keeping your elbows by your sides.",
      "Lower slowly to straight arms.",
    ],
    commonMistakes: ["Swinging the torso.", "Elbows drifting forward."],
  }),
  ex({
    id: "hammer-curl",
    name: "Hammer Curl",
    pattern: "elbow_flexion",
    mechanics: "isolation",
    primaryMuscles: ["biceps", "forearms"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    instructions: [
      "Hold dumbbells at your sides with palms facing each other.",
      "Curl up keeping the neutral grip.",
      "Lower under control.",
    ],
    commonMistakes: ["Using momentum.", "Partial range of motion."],
  }),
  ex({
    id: "barbell-curl",
    name: "Barbell Curl",
    pattern: "elbow_flexion",
    mechanics: "isolation",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    equipment: ["barbell"],
    difficulty: "beginner",
    instructions: [
      "Hold the bar with an underhand grip at shoulder width.",
      "Curl the bar up while keeping your elbows at your sides.",
      "Lower slowly to full extension.",
    ],
    commonMistakes: ["Leaning back to swing the bar.", "Not fully extending the arms."],
  }),
  ex({
    id: "cable-curl",
    name: "Cable Curl",
    pattern: "elbow_flexion",
    mechanics: "isolation",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    equipment: ["cable"],
    difficulty: "beginner",
    instructions: [
      "Attach a straight bar or rope to a low pulley.",
      "Curl the handle up keeping elbows fixed at your sides.",
      "Lower under control.",
    ],
    commonMistakes: ["Standing too close to the stack.", "Elbows moving forward."],
  }),
  ex({
    id: "band-curl",
    name: "Resistance Band Curl",
    pattern: "elbow_flexion",
    mechanics: "isolation",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    equipment: ["resistance_band"],
    difficulty: "beginner",
    instructions: [
      "Stand on the band and hold the ends with palms forward.",
      "Curl your hands toward your shoulders.",
      "Lower slowly against the tension.",
    ],
    commonMistakes: ["Letting the band snap down.", "Swinging."],
  }),
  ex({
    id: "triceps-pushdown",
    name: "Cable Triceps Pushdown",
    pattern: "elbow_extension",
    mechanics: "isolation",
    primaryMuscles: ["triceps"],
    equipment: ["cable"],
    difficulty: "beginner",
    instructions: [
      "Attach a rope or bar to a high pulley.",
      "With elbows tucked at your sides, push the handle down until your arms are straight.",
      "Let it return slowly to about chest height.",
    ],
    commonMistakes: ["Elbows flaring out.", "Leaning over the handle to push with bodyweight."],
  }),
  ex({
    id: "band-triceps-pushdown",
    name: "Resistance Band Triceps Pushdown",
    pattern: "elbow_extension",
    mechanics: "isolation",
    primaryMuscles: ["triceps"],
    equipment: ["resistance_band"],
    difficulty: "beginner",
    instructions: [
      "Anchor the band high (top of a door).",
      "Keep elbows at your sides and push down until your arms are straight.",
      "Return slowly.",
    ],
    commonMistakes: ["Elbows drifting forward.", "Insecure anchor."],
  }),
  ex({
    id: "overhead-dumbbell-triceps-extension",
    name: "Overhead Dumbbell Triceps Extension",
    pattern: "elbow_extension",
    mechanics: "isolation",
    primaryMuscles: ["triceps"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    contraindications: ["avoid_overhead"],
    instructions: [
      "Hold one dumbbell with both hands overhead, arms straight.",
      "Bend your elbows to lower the weight behind your head.",
      "Extend back to straight arms while keeping elbows pointing forward.",
    ],
    commonMistakes: ["Elbows flaring wide.", "Arching the lower back."],
  }),
  ex({
    id: "dumbbell-skull-crusher",
    name: "Dumbbell Skull Crusher",
    pattern: "elbow_extension",
    mechanics: "isolation",
    primaryMuscles: ["triceps"],
    equipment: ["dumbbell"],
    difficulty: "intermediate",
    instructions: [
      "Lie on a bench holding dumbbells above your chest with palms facing each other.",
      "Bend only at the elbows to lower the weights beside your head.",
      "Extend back to straight arms.",
    ],
    commonMistakes: ["Moving the upper arms.", "Going too heavy and losing control."],
  }),
  ex({
    id: "close-grip-bench-press",
    name: "Close-Grip Bench Press",
    pattern: "elbow_extension",
    mechanics: "compound",
    primaryMuscles: ["triceps"],
    secondaryMuscles: ["chest", "shoulders"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    instructions: [
      "Lie on a bench and grip the bar about shoulder width apart.",
      "Lower the bar to your lower chest keeping elbows close to your body.",
      "Press back up to straight arms.",
    ],
    commonMistakes: ["Grip too narrow, stressing the wrists.", "Elbows flaring out."],
  }),
  ex({
    id: "bench-dip",
    name: "Bench Dip",
    pattern: "elbow_extension",
    mechanics: "compound",
    primaryMuscles: ["triceps"],
    secondaryMuscles: ["chest", "shoulders"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    contraindications: ["wrist_friendly"],
    instructions: [
      "Sit on the edge of a sturdy bench or chair with hands beside your hips.",
      "Slide your hips forward off the edge with knees bent.",
      "Bend your elbows to lower yourself a comfortable depth, then press back up.",
    ],
    commonMistakes: ["Dropping too low and straining the front of the shoulders.", "Using an unstable chair."],
  }),
  ex({
    id: "diamond-push-up",
    name: "Diamond Push-up",
    pattern: "elbow_extension",
    mechanics: "compound",
    primaryMuscles: ["triceps"],
    secondaryMuscles: ["chest", "shoulders", "core"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    contraindications: ["avoid_floor_work", "wrist_friendly"],
    instructions: [
      "Get into a push-up position with your hands close together under your chest.",
      "Lower your chest toward your hands keeping elbows close.",
      "Push back up to straight arms.",
    ],
    commonMistakes: ["Hips sagging.", "Elbows flaring wide."],
  }),

  /* ---------------- Squat ---------------- */
  ex({
    id: "barbell-back-squat",
    name: "Barbell Back Squat",
    pattern: "squat",
    mechanics: "compound",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings", "core", "lower_back"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    contraindications: ["avoid_spinal_loading", "avoid_deep_knee_flexion"],
    instructions: [
      "Set the bar in a rack at about chest height and place it across your upper back.",
      "Stand with feet about shoulder width apart, toes slightly out.",
      "Brace your core and sit down and back, knees tracking over your toes.",
      "Descend to a depth you can control with a neutral spine, then drive back up.",
      "Use safety pins or spotter arms.",
    ],
    commonMistakes: ["Knees caving inward.", "Heels lifting.", "Rounding the lower back at the bottom."],
  }),
  ex({
    id: "front-squat",
    name: "Barbell Front Squat",
    pattern: "squat",
    mechanics: "compound",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes", "core"],
    equipment: ["barbell"],
    difficulty: "advanced",
    contraindications: ["avoid_spinal_loading", "avoid_deep_knee_flexion", "wrist_friendly"],
    instructions: [
      "Rest the bar on the front of your shoulders with elbows high.",
      "Keep your torso upright and squat down between your legs.",
      "Drive up keeping your elbows high.",
    ],
    commonMistakes: ["Elbows dropping, causing the bar to roll forward.", "Torso folding forward."],
  }),
  ex({
    id: "goblet-squat",
    name: "Goblet Squat",
    pattern: "squat",
    mechanics: "compound",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["core", "adductors"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    contraindications: ["avoid_deep_knee_flexion"],
    instructions: [
      "Hold one dumbbell vertically against your chest.",
      "Stand with feet slightly wider than hip width.",
      "Squat down keeping your chest up and elbows inside your knees.",
      "Drive through your whole foot to stand up.",
    ],
    commonMistakes: ["Heels lifting.", "Chest collapsing forward."],
  }),
  ex({
    id: "bodyweight-squat",
    name: "Bodyweight Squat",
    pattern: "squat",
    mechanics: "compound",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    contraindications: ["avoid_deep_knee_flexion"],
    instructions: [
      "Stand with feet shoulder width apart, arms in front for balance.",
      "Sit your hips down and back while keeping your chest up.",
      "Go as low as you can control, then stand back up.",
    ],
    commonMistakes: ["Knees caving in.", "Rising onto the toes."],
  }),
  ex({
    id: "box-squat",
    name: "Box Squat (to Bench)",
    pattern: "squat",
    mechanics: "compound",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    instructions: [
      "Stand in front of a sturdy bench or box at a height that feels comfortable.",
      "Sit back until you lightly touch the box, without fully relaxing.",
      "Stand back up by driving through your heels.",
      "A higher box limits how far your knees bend.",
    ],
    commonMistakes: ["Dropping onto the box.", "Rocking back to generate momentum."],
  }),
  ex({
    id: "leg-press",
    name: "Leg Press",
    pattern: "squat",
    mechanics: "compound",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["machine"],
    difficulty: "beginner",
    contraindications: ["avoid_deep_knee_flexion"],
    instructions: [
      "Sit with your back flat against the pad and feet shoulder width on the platform.",
      "Release the safeties and lower the platform until your knees are about 90°.",
      "Press back up without locking your knees.",
    ],
    commonMistakes: ["Lowering so far your lower back peels off the pad.", "Locking out the knees."],
  }),
  ex({
    id: "band-squat",
    name: "Resistance Band Squat",
    pattern: "squat",
    mechanics: "compound",
    primaryMuscles: ["quadriceps", "glutes"],
    equipment: ["resistance_band"],
    difficulty: "beginner",
    contraindications: ["avoid_deep_knee_flexion"],
    instructions: [
      "Stand on the band with feet shoulder width apart and hold the ends at your shoulders.",
      "Squat down keeping your chest up.",
      "Stand up against the band's resistance.",
    ],
    commonMistakes: ["Letting the band pull you forward.", "Knees caving in."],
  }),

  /* ---------------- Hinge ---------------- */
  ex({
    id: "conventional-deadlift",
    name: "Conventional Deadlift",
    pattern: "hinge",
    mechanics: "compound",
    primaryMuscles: ["hamstrings", "glutes", "lower_back"],
    secondaryMuscles: ["back", "traps", "forearms", "quadriceps"],
    equipment: ["barbell"],
    difficulty: "advanced",
    contraindications: ["avoid_spinal_loading"],
    instructions: [
      "Stand with mid-foot under the bar, feet about hip width.",
      "Hinge down and grip the bar just outside your legs.",
      "Brace, flatten your back, and push the floor away to stand up with the bar close to your body.",
      "Lower by pushing the hips back, keeping the bar close.",
    ],
    commonMistakes: ["Rounding the lower back.", "Bar drifting away from the legs.", "Jerking the bar off the floor."],
  }),
  ex({
    id: "romanian-deadlift",
    name: "Barbell Romanian Deadlift",
    pattern: "hinge",
    mechanics: "compound",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["lower_back", "forearms"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    contraindications: ["avoid_spinal_loading"],
    instructions: [
      "Stand holding the bar at hip height with soft knees.",
      "Push your hips back and slide the bar down your thighs with a flat back.",
      "Stop when you feel a strong hamstring stretch, then drive the hips forward to stand.",
    ],
    commonMistakes: ["Squatting the weight down instead of hinging.", "Rounding the back to reach lower."],
  }),
  ex({
    id: "dumbbell-romanian-deadlift",
    name: "Dumbbell Romanian Deadlift",
    pattern: "hinge",
    mechanics: "compound",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["lower_back", "forearms"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    instructions: [
      "Hold dumbbells in front of your thighs with soft knees.",
      "Hinge at the hips, sliding the weights down your legs with a flat back.",
      "Stand back up by squeezing your glutes.",
    ],
    commonMistakes: ["Rounding the back.", "Bending the knees too much."],
  }),
  ex({
    id: "glute-bridge",
    name: "Glute Bridge",
    pattern: "hinge",
    mechanics: "compound",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    contraindications: ["avoid_floor_work"],
    instructions: [
      "Lie on your back with knees bent and feet flat, hip width apart.",
      "Press through your heels to lift your hips until your body is straight from knees to shoulders.",
      "Squeeze your glutes at the top, then lower slowly.",
    ],
    commonMistakes: ["Arching the lower back at the top.", "Pushing through the toes."],
  }),
  ex({
    id: "single-leg-glute-bridge",
    name: "Single-Leg Glute Bridge",
    pattern: "hinge",
    mechanics: "compound",
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["core"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    contraindications: ["avoid_floor_work"],
    instructions: [
      "Lie on your back with one knee bent and the other leg extended.",
      "Drive through the planted heel to lift your hips level.",
      "Lower slowly, complete all reps, then switch legs.",
    ],
    commonMistakes: ["Hips tilting to one side.", "Overarching the lower back."],
  }),
  ex({
    id: "dumbbell-hip-thrust",
    name: "Dumbbell Hip Thrust",
    pattern: "hinge",
    mechanics: "compound",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    contraindications: ["avoid_floor_work"],
    instructions: [
      "Sit with your upper back against a bench and a dumbbell resting on your hips.",
      "Plant your feet and drive your hips up until your torso is parallel to the floor.",
      "Pause and squeeze your glutes, then lower.",
    ],
    commonMistakes: ["Hyperextending the lower back.", "Feet placed too far away."],
  }),
  ex({
    id: "barbell-hip-thrust",
    name: "Barbell Hip Thrust",
    pattern: "hinge",
    mechanics: "compound",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    contraindications: ["avoid_floor_work"],
    instructions: [
      "Sit with your upper back on a bench and roll a padded barbell over your hips.",
      "Drive your hips up until your torso is parallel to the floor, chin tucked.",
      "Lower under control.",
    ],
    commonMistakes: ["Overarching at the top.", "Not using a bar pad."],
  }),
  ex({
    id: "kettlebell-swing",
    name: "Kettlebell Swing",
    pattern: "hinge",
    mechanics: "compound",
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["core", "lower_back", "shoulders"],
    equipment: ["kettlebell"],
    difficulty: "intermediate",
    instructions: [
      "Stand with feet slightly wider than hips, kettlebell a little in front of you.",
      "Hike the bell back between your legs by hinging at the hips.",
      "Snap your hips forward to float the bell to about chest height.",
      "Let it swing back and repeat — power comes from the hips, not the arms.",
    ],
    commonMistakes: ["Squatting instead of hinging.", "Lifting with the arms.", "Rounding the back."],
  }),
  ex({
    id: "band-good-morning",
    name: "Resistance Band Good Morning",
    pattern: "hinge",
    mechanics: "compound",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["lower_back"],
    equipment: ["resistance_band"],
    difficulty: "beginner",
    instructions: [
      "Stand on the band and loop the other end behind your neck/upper back.",
      "With soft knees, hinge forward at the hips keeping your back flat.",
      "Return to standing by driving the hips forward.",
    ],
    commonMistakes: ["Rounding the spine.", "Using a band that is too strong."],
  }),
  ex({
    id: "cable-pull-through",
    name: "Cable Pull-Through",
    pattern: "hinge",
    mechanics: "compound",
    primaryMuscles: ["glutes", "hamstrings"],
    equipment: ["cable"],
    difficulty: "beginner",
    instructions: [
      "Attach a rope to a low pulley and face away, holding the rope between your legs.",
      "Hinge back, letting the rope pass between your legs.",
      "Drive your hips forward to stand tall.",
    ],
    commonMistakes: ["Pulling with the arms.", "Squatting down instead of hinging."],
  }),

  /* ---------------- Lunge / single leg ---------------- */
  ex({
    id: "dumbbell-reverse-lunge",
    name: "Dumbbell Reverse Lunge",
    pattern: "lunge",
    mechanics: "compound",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings", "adductors"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    contraindications: ["avoid_deep_knee_flexion"],
    instructions: [
      "Stand tall holding dumbbells at your sides.",
      "Step one foot back and lower until both knees are bent about 90°.",
      "Push through the front heel to return, then alternate legs.",
    ],
    commonMistakes: ["Front knee collapsing inward.", "Leaning far forward."],
  }),
  ex({
    id: "bodyweight-reverse-lunge",
    name: "Bodyweight Reverse Lunge",
    pattern: "lunge",
    mechanics: "compound",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    contraindications: ["avoid_deep_knee_flexion"],
    instructions: [
      "Stand tall, then step one foot back.",
      "Lower until your back knee nearly touches the floor.",
      "Drive through the front foot to return and alternate legs.",
    ],
    commonMistakes: ["Short steps that push the front knee far forward.", "Losing balance by rushing."],
  }),
  ex({
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    pattern: "lunge",
    mechanics: "compound",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["adductors", "hamstrings"],
    equipment: ["dumbbell"],
    difficulty: "intermediate",
    contraindications: ["avoid_deep_knee_flexion"],
    instructions: [
      "Stand in front of a bench and rest the top of your back foot on it.",
      "Hold dumbbells at your sides and lower until your front thigh is about parallel.",
      "Drive up through the front foot; complete reps then switch legs.",
    ],
    commonMistakes: ["Front foot too close to the bench.", "Bouncing at the bottom."],
  }),
  ex({
    id: "step-up",
    name: "Step-up",
    pattern: "lunge",
    mechanics: "compound",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings", "calves"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    instructions: [
      "Stand facing a sturdy step or box at about knee height or lower.",
      "Place one foot on it and push through that heel to step up.",
      "Step down with control and alternate legs.",
    ],
    commonMistakes: ["Pushing off the back foot.", "Using a box that is too high or unstable."],
  }),
  ex({
    id: "walking-lunge",
    name: "Dumbbell Walking Lunge",
    pattern: "lunge",
    mechanics: "compound",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings", "adductors", "core"],
    equipment: ["dumbbell"],
    difficulty: "intermediate",
    contraindications: ["avoid_deep_knee_flexion"],
    instructions: [
      "Hold dumbbells at your sides and step forward into a lunge.",
      "Lower until both knees are about 90°.",
      "Push through the front foot and step the back foot forward into the next lunge.",
    ],
    commonMistakes: ["Narrow 'tightrope' stance.", "Torso collapsing forward."],
  }),

  /* ---------------- Knee extension / flexion / calves ---------------- */
  ex({
    id: "leg-extension",
    name: "Leg Extension",
    pattern: "knee_extension",
    mechanics: "isolation",
    primaryMuscles: ["quadriceps"],
    equipment: ["machine"],
    difficulty: "beginner",
    instructions: [
      "Adjust the machine so your knees line up with its pivot point.",
      "Extend your legs until they are straight.",
      "Lower slowly.",
    ],
    commonMistakes: ["Kicking the weight up.", "Lifting the hips off the seat."],
  }),
  ex({
    id: "lying-leg-curl",
    name: "Lying Leg Curl",
    pattern: "knee_flexion",
    mechanics: "isolation",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["calves"],
    equipment: ["machine"],
    difficulty: "beginner",
    instructions: [
      "Lie face down with the pad just above your heels.",
      "Curl your heels toward your glutes.",
      "Lower slowly to straight legs.",
    ],
    commonMistakes: ["Hips lifting off the pad.", "Dropping the weight on the way down."],
  }),
  ex({
    id: "standing-calf-raise",
    name: "Standing Calf Raise",
    pattern: "calf_raise",
    mechanics: "isolation",
    primaryMuscles: ["calves"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    instructions: [
      "Stand on the edge of a step with heels hanging off, holding something for balance.",
      "Rise up onto your toes as high as you can.",
      "Lower your heels slowly below the step level.",
      "Hold a dumbbell to make it harder.",
    ],
    commonMistakes: ["Bouncing quickly.", "Bending the knees to help."],
  }),
  ex({
    id: "machine-calf-raise",
    name: "Machine Calf Raise",
    pattern: "calf_raise",
    mechanics: "isolation",
    primaryMuscles: ["calves"],
    equipment: ["machine"],
    difficulty: "beginner",
    instructions: [
      "Position your shoulders under the pads with the balls of your feet on the platform.",
      "Rise as high as possible onto your toes.",
      "Lower slowly to a full stretch.",
    ],
    commonMistakes: ["Short, bouncy reps.", "Knees bending."],
  }),

  /* ---------------- Core ---------------- */
  ex({
    id: "plank",
    name: "Forearm Plank",
    category: "core",
    pattern: "core_anti_extension",
    mechanics: "isolation",
    primaryMuscles: ["core"],
    secondaryMuscles: ["shoulders", "glutes"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    measure: "time",
    contraindications: ["avoid_floor_work"],
    instructions: [
      "Rest on your forearms with elbows under your shoulders.",
      "Extend your legs and form a straight line from head to heels.",
      "Brace your abs and squeeze your glutes; breathe steadily.",
    ],
    commonMistakes: ["Hips sagging.", "Hips piked high.", "Holding your breath."],
  }),
  ex({
    id: "dead-bug",
    name: "Dead Bug",
    category: "core",
    pattern: "core_anti_extension",
    mechanics: "isolation",
    primaryMuscles: ["core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    contraindications: ["avoid_floor_work"],
    instructions: [
      "Lie on your back with arms pointing up and knees bent at 90° above your hips.",
      "Press your lower back gently into the floor.",
      "Slowly extend the opposite arm and leg, then return and switch sides.",
    ],
    commonMistakes: ["Lower back arching off the floor.", "Moving too fast."],
  }),
  ex({
    id: "bird-dog",
    name: "Bird Dog",
    category: "core",
    pattern: "core_anti_extension",
    mechanics: "isolation",
    primaryMuscles: ["core", "lower_back"],
    secondaryMuscles: ["glutes"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    contraindications: ["avoid_floor_work"],
    instructions: [
      "Start on hands and knees with a neutral spine.",
      "Extend one arm forward and the opposite leg back until level with your torso.",
      "Pause, return, and alternate sides.",
    ],
    commonMistakes: ["Rotating the hips.", "Arching the lower back."],
  }),
  ex({
    id: "side-plank",
    name: "Side Plank",
    category: "core",
    pattern: "core_rotation",
    mechanics: "isolation",
    primaryMuscles: ["obliques", "core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    measure: "time",
    contraindications: ["avoid_floor_work"],
    instructions: [
      "Lie on your side with your elbow under your shoulder.",
      "Lift your hips so your body forms a straight line.",
      "Hold, then switch sides.",
    ],
    commonMistakes: ["Hips dropping.", "Rolling forward or backward."],
  }),
  ex({
    id: "band-pallof-press",
    name: "Resistance Band Pallof Press",
    category: "core",
    pattern: "core_rotation",
    mechanics: "isolation",
    primaryMuscles: ["obliques", "core"],
    equipment: ["resistance_band"],
    difficulty: "beginner",
    instructions: [
      "Anchor the band at chest height and stand side-on to the anchor.",
      "Hold the band at your chest and press it straight out in front of you.",
      "Resist the pull toward the anchor, then bring it back. Switch sides.",
    ],
    commonMistakes: ["Letting the torso twist.", "Standing too close to the anchor."],
  }),
  ex({
    id: "cable-pallof-press",
    name: "Cable Pallof Press",
    category: "core",
    pattern: "core_rotation",
    mechanics: "isolation",
    primaryMuscles: ["obliques", "core"],
    equipment: ["cable"],
    difficulty: "beginner",
    instructions: [
      "Set a cable at chest height and stand side-on to the machine.",
      "Press the handle straight out from your chest and hold briefly.",
      "Return without letting your torso rotate. Switch sides.",
    ],
    commonMistakes: ["Rotating toward the machine.", "Shrugging the shoulders."],
  }),
  ex({
    id: "hanging-knee-raise",
    name: "Hanging Knee Raise",
    category: "core",
    pattern: "core_flexion",
    mechanics: "isolation",
    primaryMuscles: ["core", "hip_flexors"],
    secondaryMuscles: ["forearms"],
    equipment: ["pullup_bar"],
    difficulty: "intermediate",
    instructions: [
      "Hang from a pull-up bar with straight arms.",
      "Curl your knees up toward your chest by tilting your pelvis.",
      "Lower slowly without swinging.",
    ],
    commonMistakes: ["Swinging for momentum.", "Only lifting the legs without curling the pelvis."],
  }),
  ex({
    id: "crunch",
    name: "Crunch",
    category: "core",
    pattern: "core_flexion",
    mechanics: "isolation",
    primaryMuscles: ["core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    contraindications: ["avoid_floor_work"],
    instructions: [
      "Lie on your back with knees bent and hands lightly by your ears or across your chest.",
      "Curl your shoulders off the floor by contracting your abs.",
      "Lower slowly.",
    ],
    commonMistakes: ["Pulling on the neck.", "Using momentum."],
  }),
  ex({
    id: "cable-crunch",
    name: "Kneeling Cable Crunch",
    category: "core",
    pattern: "core_flexion",
    mechanics: "isolation",
    primaryMuscles: ["core"],
    equipment: ["cable"],
    difficulty: "intermediate",
    contraindications: ["avoid_floor_work"],
    instructions: [
      "Kneel facing a high pulley holding a rope beside your head.",
      "Crunch down by flexing your spine, bringing elbows toward your thighs.",
      "Return slowly.",
    ],
    commonMistakes: ["Sitting back with the hips instead of flexing the spine.", "Pulling with the arms."],
  }),
  ex({
    id: "farmers-carry",
    name: "Farmer's Carry",
    category: "strength",
    pattern: "carry",
    mechanics: "compound",
    primaryMuscles: ["forearms", "traps"],
    secondaryMuscles: ["core", "glutes"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    measure: "time",
    instructions: [
      "Pick up heavy dumbbells and stand tall.",
      "Walk with short, controlled steps keeping your shoulders back.",
      "Set the weights down with a flat back when the time is up.",
    ],
    commonMistakes: ["Leaning to one side.", "Shrugging or rounding the shoulders."],
  }),
  ex({
    id: "suitcase-carry",
    name: "Suitcase Carry",
    category: "core",
    pattern: "carry",
    mechanics: "compound",
    primaryMuscles: ["obliques", "core"],
    secondaryMuscles: ["forearms", "traps"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    measure: "time",
    instructions: [
      "Hold one dumbbell at your side.",
      "Walk while keeping your torso upright — don't lean toward the weight.",
      "Switch hands halfway.",
    ],
    commonMistakes: ["Leaning toward or away from the weight.", "Rushing the steps."],
  }),

  /* ---------------- Conditioning ---------------- */
  ex({
    id: "jumping-jacks",
    name: "Jumping Jacks",
    category: "cardio",
    pattern: "conditioning",
    mechanics: "compound",
    primaryMuscles: ["full_body"],
    secondaryMuscles: ["calves", "shoulders"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    measure: "time",
    contraindications: ["avoid_jumping"],
    instructions: [
      "Stand with feet together and arms at your sides.",
      "Jump your feet out while raising your arms overhead.",
      "Jump back to the start and repeat at a steady pace.",
    ],
    commonMistakes: ["Landing heavily on the heels.", "Going too fast and losing rhythm."],
  }),
  ex({
    id: "step-jacks",
    name: "Low-Impact Step Jacks",
    category: "cardio",
    pattern: "conditioning",
    mechanics: "compound",
    primaryMuscles: ["full_body"],
    secondaryMuscles: ["calves", "shoulders"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    measure: "time",
    instructions: [
      "Step one foot out to the side while raising your arms.",
      "Step back in and lower your arms, then switch sides.",
      "Keep a brisk, steady pace without jumping.",
    ],
    commonMistakes: ["Slowing down so much your heart rate drops.", "Hunching the shoulders."],
  }),
  ex({
    id: "burpee",
    name: "Burpee",
    category: "cardio",
    pattern: "conditioning",
    mechanics: "compound",
    primaryMuscles: ["full_body"],
    secondaryMuscles: ["chest", "quadriceps", "core"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    contraindications: ["avoid_jumping", "avoid_floor_work", "wrist_friendly"],
    instructions: [
      "From standing, squat and place your hands on the floor.",
      "Jump or step your feet back into a plank.",
      "Return your feet to your hands and stand or jump up.",
    ],
    commonMistakes: ["Letting the hips sag in the plank.", "Landing with stiff knees."],
  }),
  ex({
    id: "mountain-climber",
    name: "Mountain Climber",
    category: "cardio",
    pattern: "conditioning",
    mechanics: "compound",
    primaryMuscles: ["core", "full_body"],
    secondaryMuscles: ["shoulders", "hip_flexors"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    measure: "time",
    contraindications: ["avoid_floor_work", "wrist_friendly"],
    instructions: [
      "Start in a high plank with hands under shoulders.",
      "Drive one knee toward your chest, then switch legs quickly.",
      "Keep your hips level throughout.",
    ],
    commonMistakes: ["Hips bouncing up and down.", "Hands drifting forward of the shoulders."],
  }),
  ex({
    id: "high-knees",
    name: "High Knees",
    category: "cardio",
    pattern: "conditioning",
    mechanics: "compound",
    primaryMuscles: ["full_body"],
    secondaryMuscles: ["hip_flexors", "calves", "quadriceps"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    measure: "time",
    contraindications: ["avoid_jumping", "avoid_running"],
    instructions: [
      "Run in place, driving your knees up toward hip height.",
      "Pump your arms and stay on the balls of your feet.",
    ],
    commonMistakes: ["Leaning back.", "Landing heavily."],
  }),
  ex({
    id: "shadow-boxing",
    name: "Shadow Boxing",
    category: "cardio",
    pattern: "conditioning",
    mechanics: "compound",
    primaryMuscles: ["full_body"],
    secondaryMuscles: ["shoulders", "core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    measure: "time",
    instructions: [
      "Stand in a staggered stance with hands up by your face.",
      "Throw controlled punch combinations while moving your feet.",
      "Keep a pace that leaves you breathing hard but in control.",
    ],
    commonMistakes: ["Locking out the elbows on punches.", "Dropping your guard between punches."],
  }),
  ex({
    id: "stationary-bike",
    name: "Stationary Bike",
    category: "cardio",
    pattern: "conditioning",
    mechanics: "compound",
    primaryMuscles: ["quadriceps", "full_body"],
    secondaryMuscles: ["glutes", "calves"],
    equipment: ["machine"],
    difficulty: "beginner",
    measure: "time",
    loaded: false,
    instructions: [
      "Adjust the seat so your knee is slightly bent at the bottom of the pedal stroke.",
      "Pedal at a steady pace, adjusting resistance to the target effort.",
      "Cool down with easy pedaling at the end.",
    ],
    commonMistakes: ["Seat too low.", "Resistance so low you are just spinning."],
  }),
  ex({
    id: "rowing-machine",
    name: "Rowing Machine",
    category: "cardio",
    pattern: "conditioning",
    mechanics: "compound",
    primaryMuscles: ["full_body", "back"],
    secondaryMuscles: ["quadriceps", "glutes", "biceps"],
    equipment: ["machine"],
    difficulty: "intermediate",
    measure: "time",
    loaded: false,
    instructions: [
      "Strap your feet in and grab the handle.",
      "Drive with your legs first, then lean back slightly and pull the handle to your lower ribs.",
      "Reverse the order to return: arms, body, then legs.",
    ],
    commonMistakes: ["Pulling with the arms before the legs.", "Rounding the back."],
  }),
  ex({
    id: "treadmill-run",
    name: "Treadmill Run",
    category: "cardio",
    pattern: "conditioning",
    mechanics: "compound",
    primaryMuscles: ["full_body", "quadriceps"],
    secondaryMuscles: ["calves", "hamstrings", "glutes"],
    equipment: ["machine"],
    difficulty: "beginner",
    measure: "time",
    loaded: false,
    contraindications: ["avoid_running", "avoid_jumping"],
    instructions: [
      "Start with a few minutes of walking to warm up.",
      "Increase to a comfortable running pace.",
      "Keep a relaxed upper body and land under your hips.",
    ],
    commonMistakes: ["Holding the handrails.", "Overstriding."],
  }),
  ex({
    id: "incline-treadmill-walk",
    name: "Incline Treadmill Walk",
    category: "cardio",
    pattern: "conditioning",
    mechanics: "compound",
    primaryMuscles: ["full_body", "glutes"],
    secondaryMuscles: ["calves", "hamstrings"],
    equipment: ["machine"],
    difficulty: "beginner",
    measure: "time",
    loaded: false,
    instructions: [
      "Set a brisk walking speed and a moderate incline.",
      "Walk tall without holding onto the rails.",
      "Lower the incline if you need to hold on to keep up.",
    ],
    commonMistakes: ["Leaning on the handrails.", "Choosing an incline that forces a hunched posture."],
  }),
];
